version: '3'

networks:
  laravel:

services:
  
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: unless-stopped
    ports: 
      - "8080:80"
      - "443:443"
    tty: true
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes:
      - /private/var/lib/mysql:/var/lib/mysql
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: imonit
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  redis:
    image: 'bitnami/redis:5.0'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'  

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel
    env_file:
      - ./dock-compose.env

volumes:
  mysql_db:
    external:
      name: mysql_db
  redis_data:
    driver: local